name: Re-Publish NVIDIA Studio Driver Package

on:
  workflow_dispatch:

jobs:
    republish-nvidia-studio-driver:
        runs-on: windows-latest
        env:
            GH_TOKEN: ${{ github.token }}
            api_key: ${{ secrets.CHOCOLATEY }}
            packageName: nvidia-studio-driver
        steps:
            - uses: actions/checkout@v4
            - uses: fregante/setup-git-user@v2.0.2
            - name: Run Update Script for NVIDIA Studio Driver Package
              run: |
                "Run Update Script for NVIDIA Studio Driver Package" | Out-Host;
                cd $env:packageName
                pwsh .\update.ps1 -republish