name: Update NVIDIA Studio Driver Package

on:
  workflow_dispatch:
  schedule:
  - cron: "0 8 * * *"


jobs:
    update-nvidia-studio-driver:
        runs-on: windows-latest
        env:
            GH_TOKEN: ${{ github.token }}
            api_key: ${{ secrets.CHOCOLATEY }}
            packageName: nvidia-studio-driver
        steps:
            - uses: actions/checkout@v4
            - uses: fregante/setup-git-user@v2.0.2
            - name: Run Update Script for NVIDIA Studio Driver Package
              run: |
                cd $env:packageName
                pwsh .\update.ps1